/**
 * @module config/fileHeader.js
 * @description create custom file header for style dictionary tokens.
 * @license MIT
 * @author Sandeep Upadhyay
 */

import fs from 'fs';
import StyleDictionary from 'style-dictionary';

// Add package.json version to the file header
const packageJson = JSON.parse(
  fs.readFileSync(new URL('../package.json', import.meta.url), 'utf8')
);
const version = packageJson.version;

/**
 * Custom file header for generated tokens.
 * @returns {string[]} - an array of header comment lines.
 */
export function customFileHeader() {
  return [
    `/**
      * @module tokens
      * @description Style Dictionary tokens generated by the design system.
      * This file is auto-generated by Style Dictionary.
      * Do not edit directly.
      * Instead, modify the source files and run the build script.
      * @file ${StyleDictionary.fileHeader.fileName}
      * @date ${new Date().toISOString()}
      * @version ${version}
      * @license MIT
      * @author Sandeep Upadhyay
      */`,
    '',
    '/* eslint-disable */',
    '/* prettier-ignore */',
    '/* stylelint-disable */',
    '',
  ];
}

// Register the custom file header with Style Dictionary
export function registerFileHeader() {
  StyleDictionary.registerFileHeader({
    name: 'customFileHeader',
    fileHeader: customFileHeader,
  });
}